export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'
export const ADD_TODO = 'ADD_TODO'
export const COUNT_TODO = 'COUNT_TODOS'
export const TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS';
export const DELETE_TODO = 'DELETE_TODO'